// managed-plugin-wrapper — REQ-128 Phase 4 `#809`(已批基线 §4 D1 实现形态第 4 条 + §4 D4)。
//
// 一个 managed plugin 在盘上是**两个**文件,不是一个:
//   · `upstream.js` —— 第三方的字节,**逐字节不改**;
//   · `plugin.js`   —— 本模块生成的 strict V1 wrapper,`plugin[]` 里写的是它的绝对路径。
//
// wrapper 存在的理由有三条,都不是「加一层更整齐」:
//
//   ① **归一化 ABI 分支。** `applyPlugin`(`packages/opencode/src/plugin/index.ts:110-117`)先跑
//      detect,wrapper 命中即 `:115 return`,legacy 分支结构性不可达。裸文件走的是 legacy 分支
//      —— 那条分支的语义是「把模块的每个导出值都当插件工厂」,**取决于第三方怎么写它的导出表**。
//      managed 路径不该把装载语义外包给第三方下一版的导出表。
//   ② **归一化身份。** detect 分支会调 `resolvePluginId`(`:113`),wrapper 给出由组件 id 派生的
//      确定性 `id`;legacy 分支跳过它(`:118`)⇒ 裸文件装进来是**无 id 的**。
//   ③ **关掉第二个加载器那条腿(§4 D4)。** `plugin[]` 里那个绝对路径会被**两个**加载器各求值
//      一遍:V1 `applyPlugin`,以及 V2 `ConfigExternalPlugin`
//      (`packages/core/src/config/plugin/external.ts:75-87`,ABI 是 `{id, effect}` / `{id, setup}`,
//      解码失败被 `Effect.ignoreCause` **静默**丢弃)。V2 那次 `import()` 照样发生 ——
//      所以本模板**顶层不 import 上游**:`import("./upstream.js")` 写在 `server()` 函数体内。
//      ⇒ V2 求值到的是一个**零副作用**的模块(一个字符串常量 + 一个函数声明),第三方字节
//      从头到尾没被 V2 求值过。这一条替掉了「在配置投影层全局剥 `plugin` 键」那个方案 ——
//      后者会把用户自己配的**所有**合法 V2 插件一起关掉。
//
// **不变量(落成测试,`managed-plugin-wrapper.test.ts`)**:
//   · `mod.default` 的**自有键恰为 `{id, server}`** —— 断言对准 `mod.default`,**不是** named
//     exports:V2 读的是 `mod.default.effect` / `mod.default.setup`,一个错误的 default
//     `{id, server, effect}` 会被两个加载器同时接受(唯一的双注册形状),而「模块只导出 default」
//     那条断言对它成立。
//   · 顶层零副作用:只 `import()` 不调 `server()` 的求值方,不得让第三方字节跑起来。
//
// **这套东西证明不了什么**(如实登记,不许写成等价保证):它不证明真实引擎会把 hooks 派发到
// 这个插件 —— 生产还要过 `plugin_origins` 去重、`applyPlugin` 的 detect、detect 命中后的
// `resolvePluginId`,以及派发时对 hook 值的实际调用(`plugin/index.ts:255` / `:288-290`)。
// 那一条只由打包真机证据关闭。

/** wrapper 的入口文件名。`installPluginFromCas` 的载体本来就要求顶层 `plugin.js`,managed 通道
 *  沿用同一约定 —— 两条通道在盘上的入口名不同会让「同名派生路径」那组闸各查各的。 */
export const MANAGED_PLUGIN_ENTRYPOINT_V1 = "plugin.js"
/** 第三方字节的落点。 */
export const MANAGED_PLUGIN_UPSTREAM_V1 = "upstream.js"

/**
 * 组件 id 的文法,与宿主合同 `alpha-package-envelope-v1.schema.json` 的 `id.pattern` 同源
 * (`decoder.ts` 的 `PACKAGE_ID_RE`)。这里**再查一遍**不是复述规则,是因为下面这一行把
 * 调用方给的字符串写进**会被求值的源码**:生成器对自己的输出负责,不能假定上游已经收窄过。
 */
const COMPONENT_ID_RE = /^[a-z][a-z0-9-]{0,31}:[a-z0-9][a-z0-9._-]{0,127}$/

export type ManagedPluginWrapperV1 = { ok: true; source: string } | { ok: false; reason: string }

/**
 * 由组件 id 确定性派生 wrapper 源码。同一个组件 id ⇒ 逐字节相同的输出(没有时间戳、没有随机数、
 * 没有绝对路径),否则内容寻址的落点会随每次安装漂移。
 */
export function managedPluginWrapperSourceV1(componentId: string): ManagedPluginWrapperV1 {
  if (typeof componentId !== "string" || !COMPONENT_ID_RE.test(componentId))
    return {
      ok: false,
      reason: `managed plugin wrapper: component id ${JSON.stringify(componentId)} is not a well-formed package component id — refusing to generate a module from it (fail closed)`,
    }
  // `JSON.stringify` 而不是拼引号:文法已经排除了引号与换行,但「生成源码」这件事上,靠
  // 上游文法保证转义是把决定权交给别人。两道各自成立。
  const id = JSON.stringify(componentId)
  const upstream = JSON.stringify(`./${MANAGED_PLUGIN_UPSTREAM_V1}`)
  return {
    ok: true,
    source: `// Generated by Alpha for a managed OpenCode Plugin (REQ-128). Do not edit.
//
// The upstream import is INSIDE server() on purpose: a loader that only evaluates this module
// (the V2 ConfigExternalPlugin path) must reach a side-effect-free shell, not third-party code.
const id = ${id}
async function server(input, options) {
  const upstream = await import(${upstream})
  const factory = upstream.default
  if (typeof factory !== "function")
    throw new TypeError(\`managed plugin \${id}: ${MANAGED_PLUGIN_UPSTREAM_V1} must default export a plugin factory\`)
  return factory(input, options)
}
export default { id, server }
`,
  }
}
