export const SETTINGS_STORE = "opencode.settings"
export const RENDERER_SETTINGS_STORE = "default.dat"
export const RENDERER_SETTINGS_KEY = "settings.v3"
export const DEFAULT_SERVER_URL_KEY = "defaultServerUrl"
export const WSL_SERVERS_KEY = "wslServers"
export const PINCH_ZOOM_ENABLED_KEY = "pinchZoomEnabled"
