// Regression matrix for formats removed from the REQ-093 gate by the OOXML-only owner ruling.
// This is test evidence, not a runtime authority;production inclusion derives only from
// OFFICE_OPEN_GATE_FORMATS.
export const NON_OOXML_OPEN_GATE_REGRESSION_FORMATS = [
  { extension: "doc", mimes: ["application/msword"] },
  { extension: "dot", mimes: ["application/msword"] },
  { extension: "wll", mimes: ["application/msword"] },
  { extension: "odt", mimes: ["application/vnd.oasis.opendocument.text"] },
  { extension: "rtf", mimes: ["application/rtf", "text/rtf"] },
  { extension: "wps", mimes: ["application/vnd.ms-works"] },
  { extension: "asd", mimes: ["application/msword"] },
  { extension: "wbk", mimes: ["application/msword"] },
  {
    extension: "fodt",
    mimes: ["application/vnd.oasis.opendocument.text-flat-xml", "application/vnd.oasis.opendocument.text"],
  },
  { extension: "txt", mimes: ["text/plain"] },
  { extension: "htm", mimes: ["text/html"] },
  { extension: "html", mimes: ["text/html"] },
  { extension: "mht", mimes: ["multipart/related"] },
  { extension: "mhtml", mimes: ["multipart/related"] },
  { extension: "xhtml", mimes: ["application/xhtml+xml"] },
  { extension: "xml", mimes: ["application/xml", "text/xml"] },
  { extension: "xls", mimes: ["application/vnd.ms-excel"] },
  { extension: "xlt", mimes: ["application/vnd.ms-excel"] },
  { extension: "xla", mimes: ["application/vnd.ms-excel"] },
  { extension: "xlw", mimes: ["application/vnd.ms-excel"] },
  { extension: "xlm", mimes: ["application/vnd.ms-excel"] },
  { extension: "xll", mimes: ["application/vnd.ms-excel"] },
  { extension: "xlr", mimes: ["application/vnd.ms-works"] },
  { extension: "ods", mimes: ["application/vnd.oasis.opendocument.spreadsheet"] },
  { extension: "csv", mimes: ["text/csv"] },
  { extension: "prn", mimes: ["text/plain"] },
  { extension: "tsv", mimes: ["text/tab-separated-values"] },
  { extension: "tab", mimes: ["text/tab-separated-values"] },
  { extension: "dif", mimes: ["application/vnd.ms-excel"] },
  { extension: "slk", mimes: ["application/vnd.ms-excel"] },
  { extension: "iqy", mimes: ["application/vnd.ms-excel"] },
  { extension: "oqy", mimes: ["application/vnd.ms-excel"] },
  { extension: "dqy", mimes: ["application/vnd.ms-excel"] },
  { extension: "rqy", mimes: ["application/vnd.ms-excel"] },
  { extension: "qry", mimes: ["application/vnd.ms-excel"] },
  { extension: "odc", mimes: ["application/vnd.ms-excel"] },
  { extension: "xlk", mimes: ["application/vnd.ms-excel"] },
  { extension: "xlc", mimes: ["application/vnd.ms-excel"] },
  {
    extension: "fods",
    mimes: [
      "application/vnd.oasis.opendocument.spreadsheet-flat-xml",
      "application/vnd.oasis.opendocument.spreadsheet",
    ],
  },
  { extension: "wk1", mimes: ["application/vnd.lotus-1-2-3"] },
  { extension: "wk2", mimes: ["application/vnd.lotus-1-2-3"] },
  { extension: "wk3", mimes: ["application/vnd.lotus-1-2-3"] },
  { extension: "wk4", mimes: ["application/vnd.lotus-1-2-3"] },
  { extension: "wks", mimes: ["application/vnd.lotus-1-2-3", "application/vnd.ms-works"] },
  { extension: "wq1", mimes: ["application/x-quattropro"] },
  { extension: "wb1", mimes: ["application/x-quattro-win"] },
  { extension: "wb3", mimes: ["application/x-quattro-win"] },
  { extension: "ppt", mimes: ["application/vnd.ms-powerpoint"] },
  { extension: "pot", mimes: ["application/vnd.ms-powerpoint"] },
  { extension: "pps", mimes: ["application/vnd.ms-powerpoint"] },
  { extension: "ppa", mimes: ["application/vnd.ms-powerpoint"] },
  { extension: "odp", mimes: ["application/vnd.oasis.opendocument.presentation"] },
  {
    extension: "fodp",
    mimes: [
      "application/vnd.oasis.opendocument.presentation-flat-xml",
      "application/vnd.oasis.opendocument.presentation",
    ],
  },
  { extension: "ppz", mimes: ["application/vnd.ms-powerpoint"] },
  { extension: "pdf", mimes: ["application/pdf"] },
  { extension: "xps", mimes: ["application/vnd.ms-xpsdocument"] },
  { extension: "oxps", mimes: ["application/oxps"] },
  { extension: "mp4", mimes: ["video/mp4", "audio/mp4"] },
  { extension: "mov", mimes: ["video/quicktime"] },
  { extension: "wmv", mimes: ["video/x-ms-wmv"] },
  { extension: "pages", mimes: ["application/vnd.apple.pages"] },
  { extension: "numbers", mimes: ["application/vnd.apple.numbers"] },
  { extension: "key", mimes: ["application/vnd.apple.keynote"] },
] as const
