import { type ComponentProps } from "solid-js"
import brandMark from "./brand/brand-mark.png"

// alpha-code's brand mark: the masked puppy tile (`ac#1479`). The raster is generated by
// `icons/source/make-icons.py` from the same source as the app icon, so the dock and the
// in-app mark cannot drift apart.
//
// Drop-in API match for @opencode-ai/ui/logo — same `Mark` / `Splash` / `Logo` names, props and
// viewBoxes — and still an <svg> root, so every caller's layout and `ref` type are unchanged.
// That is what lets electron.vite.config.ts alias the upstream module to this file at bundle
// time: opencode's own splash (health check / connection error) and error page then render the
// puppy without editing upstream source.

const WORDMARK_FONT = `-apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", system-ui, sans-serif`

export const Splash = (props: Pick<ComponentProps<"svg">, "ref" | "class">) => {
  return (
    <svg
      ref={props.ref}
      data-component="logo-splash"
      classList={{ [props.class ?? ""]: !!props.class }}
      viewBox="0 0 80 100"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <image href={brandMark} x="0" y="10" width="80" height="80" />
    </svg>
  )
}

export const Mark = (props: { class?: string }) => {
  return (
    <svg
      data-component="logo-mark"
      classList={{ [props.class ?? ""]: !!props.class }}
      viewBox="0 0 16 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <image href={brandMark} x="0" y="2" width="16" height="16" />
    </svg>
  )
}

export const Logo = (props: { class?: string }) => {
  return (
    <svg
      data-component="logo"
      classList={{ [props.class ?? ""]: !!props.class }}
      viewBox="0 0 234 42"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <image href={brandMark} x="0" y="0" width="42" height="42" />
      <text
        x="54"
        y="21"
        dominant-baseline="central"
        font-family={WORDMARK_FONT}
        font-weight="680"
        font-size="26"
        letter-spacing="1"
        fill="currentColor"
      >
        CODE PUPPY
      </text>
    </svg>
  )
}
